Course.create!(name: "HTML", description: "Hypertext Markup Language is the standard markup language for creating web pages and web applications.")
Course.create!(name: "CSS", description: "Cascading Style Sheets is a style sheet language used for describing the presentation of a document written in a markup language like HTML.")
Course.create!(name: "JavaScript", description: "JavaScript often abbreviated as JS is a high-level interpreted programming language that conforms to the ECMAScript specification.")
Course.create!(name: "jQuery", description: "A JavaScript library is a library of pre-written JavaScript which allows for easier development of JavaScript-based applications especially for AJAX and other web-centric technologies.")
Course.create!(name: "JSON", description: "JavaScript Object Notation (JSON) is an open-standard file format that uses human-readable text to transmit data objects consisting of attribute–value pairs and array data types (or any other serializablevalue).")
Course.create!(name: "AJAX", description: "Ajax is a set of Web development techniques using many web technologies on the client side to create asynchronous Web applications. ")
Course.create!(name: "SQL", description: "Structured Query Language) is a domain-specific language used in programming and designed for managing data held in a relational database management system (RDBMS) or for stream processing in a relational data stream management system (RDSMS). ")
Course.create!(name: "Python", description: "Python is an interpreted high-level general-purpose programming language. ")
Course.create!(name: "Java ", description: "Java is a general-purpose computer-programming language that is concurrent class-based object-oriented and specifically designed to have as few implementation dependencies as possible.")
Course.create!(name: "ASP", description: "Active Server Pages (ASP) later known as Classic ASP or ASP Classic is Microsoft's first server-side script engine for dynamically generated web pages.")
Course.create!(name: "Node.js", description: "Node.js is an open-source cross-platformJavaScript run-time environment that executes JavaScript code outside of a browser. ")
puts Course.count 

Question.create!(course_id: 1, body: "HTML elements are usually made up of two tags?", format_type: 0, difficult_level: 0)
Question.create!(course_id: 1, body: "You don't have to use a forward slash on a closing tag?", format_type: 0, difficult_level: 0)
Question.create!(course_id: 1, body: "HTML pages are text documents?", format_type: 0, difficult_level: 0)
Question.create!(course_id: 1, body: "Closing tags can carry attributes, which tell us more about the content of that element?", format_type: 0, difficult_level: 0)
Question.create!(course_id: 1, body: "Opening tags can carry attributes, which tell us more about the content of that element?", format_type: 0, difficult_level: 0)
Question.create!(course_id: 1, body: "Attributes require a name and a value?", format_type: 0, difficult_level: 0)
Question.create!(course_id: 1, body: "HTML elements are used to describe the structure of the page?", format_type: 0, difficult_level: 0)
Question.create!(course_id: 1, body: "HTML tags are used to describe the structure of the page?", format_type: 0, difficult_level: 0)
Question.create!(course_id: 1, body: "Lists can be nested inside one another?", format_type: 0, difficult_level: 0)
Question.create!(course_id: 1, body: "Lists can never be nested inside one another?", format_type: 0, difficult_level: 0)
Question.create!(course_id: 1, body: "There are three types of HTML lists: ", format_type: 1, difficult_level: 0)
Question.create!(course_id: 1, body: "Ordered list use ", format_type: 1, difficult_level: 0)
Question.create!(course_id: 1, body: "Unodered list use", format_type: 1, difficult_level: 0)
Question.create!(course_id: 1, body: "Definition list are used to ", format_type: 1, difficult_level: 0)
Question.create!(course_id: 1, body: "Links are created using", format_type: 1, difficult_level: 0)
Question.create!(course_id: 1, body: "Which attribute is used to indicate the page you are linking to from the <a> tag?", format_type: 1, difficult_level: 0)
Question.create!(course_id: 1, body: "You can create links to open email programs", format_type: 1, difficult_level: 0)
Question.create!(course_id: 1, body: "You can use the id attribute to target", format_type: 1, difficult_level: 0)
Question.create!(course_id: 1, body: "Element used to add images to a web page?", format_type: 1, difficult_level: 0)
Question.create!(course_id: 1, body: "Attribute used to indicate the source of an image?", format_type: 1, difficult_level: 0)
Question.create!(course_id: 1, body: "Attribute used to describe the content of an image?", format_type: 1, difficult_level: 0)
Question.create!(course_id: 1, body: "Photographs are best saved as ", format_type: 1, difficult_level: 0)
Question.create!(course_id: 1, body: "Illustrations or logos that use flat colors are better saved as ", format_type: 1, difficult_level: 0)
Question.create!(course_id: 1, body: "Element used to add tables to a web page?", format_type: 1, difficult_level: 0)
puts Question.count 

Answer.create!(question_id: 1, correct: true, body: "true ", display_sequence: 0)
Answer.create!(question_id: 2, correct: true, body: "FALSE", display_sequence: 0)
Answer.create!(question_id: 3, correct: true, body: "true ", display_sequence: 0)
Answer.create!(question_id: 4, correct: true, body: "FALSE", display_sequence: 0)
Answer.create!(question_id: 5, correct: true, body: "true ", display_sequence: 0)
Answer.create!(question_id: 6, correct: true, body: "true ", display_sequence: 0)
Answer.create!(question_id: 7, correct: true, body: "true ", display_sequence: 0)
Answer.create!(question_id: 8, correct: true, body: "true ", display_sequence: 0)
Answer.create!(question_id: 9, correct: true, body: "true ", display_sequence: 0)
Answer.create!(question_id: 10, correct: true, body: "FALSE", display_sequence: 0)
Answer.create!(question_id: 11, correct: true, body: "ordered, unordered, and definition.", display_sequence: 0)
Answer.create!(question_id: 11, correct: false, body: "numbered, ordered, and unordered.", display_sequence: 0)
Answer.create!(question_id: 11, correct: false, body: "number, bullets, and ordered.", display_sequence: 0)
Answer.create!(question_id: 11, correct: false, body: "numbered, alphabetic, and bullets.", display_sequence: 0)
Answer.create!(question_id: 11, correct: false, body: "intergers, strings, and symbols.", display_sequence: 0)
Answer.create!(question_id: 11, correct: false, body: "mixed, ordered, and unordered.", display_sequence: 0)
Answer.create!(question_id: 11, correct: false, body: "ordered, numbered, and definition.", display_sequence: 0)
Answer.create!(question_id: 11, correct: false, body: "ordered, bulleted, and definition.", display_sequence: 0)
Answer.create!(question_id: 11, correct: false, body: "ordered, unordered, and numbered.", display_sequence: 0)
Answer.create!(question_id: 11, correct: false, body: "ordered, unordered, and bullets.", display_sequence: 0)
Answer.create!(question_id: 11, correct: false, body: "texted, nubered, and bullets.", display_sequence: 0)
Answer.create!(question_id: 11, correct: false, body: "array, ordered, and unordered.", display_sequence: 0)
Answer.create!(question_id: 11, correct: false, body: "linked, array, and numbered.", display_sequence: 0)
Answer.create!(question_id: 11, correct: false, body: "linked, array, and ordered.", display_sequence: 0)
Answer.create!(question_id: 11, correct: false, body: "linked, array, and bullets.", display_sequence: 0)
Answer.create!(question_id: 12, correct: true, body: "numbers.", display_sequence: 0)
Answer.create!(question_id: 12, correct: false, body: "integers.", display_sequence: 0)
Answer.create!(question_id: 12, correct: false, body: "floats. ", display_sequence: 0)
Answer.create!(question_id: 12, correct: false, body: "bullets.", display_sequence: 0)
Answer.create!(question_id: 12, correct: false, body: "symbols.", display_sequence: 0)
Answer.create!(question_id: 12, correct: false, body: "alphanumeric.", display_sequence: 0)
Answer.create!(question_id: 12, correct: false, body: "boolean.", display_sequence: 0)
Answer.create!(question_id: 12, correct: false, body: "characters.", display_sequence: 0)
Answer.create!(question_id: 12, correct: false, body: "strings.", display_sequence: 0)
Answer.create!(question_id: 12, correct: false, body: "functions.", display_sequence: 0)
Answer.create!(question_id: 12, correct: false, body: "arrays.", display_sequence: 0)
Answer.create!(question_id: 12, correct: false, body: "binary.", display_sequence: 0)
Answer.create!(question_id: 12, correct: false, body: "hexadecimal.", display_sequence: 0)
Answer.create!(question_id: 12, correct: false, body: "decimals.", display_sequence: 0)
Answer.create!(question_id: 12, correct: false, body: "truthiness.", display_sequence: 0)
Answer.create!(question_id: 13, correct: true, body: "bullets.", display_sequence: 0)
Answer.create!(question_id: 13, correct: false, body: "integers.", display_sequence: 0)
Answer.create!(question_id: 13, correct: false, body: "floats. ", display_sequence: 0)
Answer.create!(question_id: 13, correct: false, body: "numbers.", display_sequence: 0)
Answer.create!(question_id: 13, correct: false, body: "symbols.", display_sequence: 0)
Answer.create!(question_id: 13, correct: false, body: "alphanumeric.", display_sequence: 0)
Answer.create!(question_id: 13, correct: false, body: "boolean.", display_sequence: 0)
Answer.create!(question_id: 13, correct: false, body: "characters.", display_sequence: 0)
Answer.create!(question_id: 13, correct: false, body: "strings.", display_sequence: 0)
Answer.create!(question_id: 13, correct: false, body: "functions.", display_sequence: 0)
Answer.create!(question_id: 13, correct: false, body: "arrays.", display_sequence: 0)
Answer.create!(question_id: 13, correct: false, body: "binary.", display_sequence: 0)
Answer.create!(question_id: 13, correct: false, body: "hexadecimal.", display_sequence: 0)
Answer.create!(question_id: 13, correct: false, body: "decimals.", display_sequence: 0)
Answer.create!(question_id: 13, correct: false, body: "truthiness.", display_sequence: 0)
Answer.create!(question_id: 14, correct: true, body: "define terminology.", display_sequence: 0)
Answer.create!(question_id: 14, correct: false, body: "define integers.", display_sequence: 0)
Answer.create!(question_id: 14, correct: false, body: "define floats. ", display_sequence: 0)
Answer.create!(question_id: 14, correct: false, body: "define numbers.", display_sequence: 0)
Answer.create!(question_id: 14, correct: false, body: "define symbols.", display_sequence: 0)
Answer.create!(question_id: 14, correct: false, body: "define alphanumeric.", display_sequence: 0)
Answer.create!(question_id: 14, correct: false, body: "define boolean.", display_sequence: 0)
Answer.create!(question_id: 14, correct: false, body: "define characters.", display_sequence: 0)
Answer.create!(question_id: 14, correct: false, body: "define strings.", display_sequence: 0)
Answer.create!(question_id: 14, correct: false, body: "define functions.", display_sequence: 0)
Answer.create!(question_id: 14, correct: false, body: "define arrays.", display_sequence: 0)
Answer.create!(question_id: 14, correct: false, body: "define binary.", display_sequence: 0)
Answer.create!(question_id: 14, correct: false, body: "define hexadecimal.", display_sequence: 0)
Answer.create!(question_id: 14, correct: false, body: "define decimals.", display_sequence: 0)
Answer.create!(question_id: 14, correct: false, body: "define truthiness.", display_sequence: 0)
Answer.create!(question_id: 15, correct: true, body: "the <a> element.", display_sequence: 0)
Answer.create!(question_id: 15, correct: false, body: "the <i> element.", display_sequence: 0)
Answer.create!(question_id: 15, correct: false, body: "the <e> element.", display_sequence: 0)
Answer.create!(question_id: 15, correct: false, body: "the <o> element.", display_sequence: 0)
Answer.create!(question_id: 15, correct: false, body: "the <u> element.", display_sequence: 0)
Answer.create!(question_id: 15, correct: false, body: "the <d> element.", display_sequence: 0)
Answer.create!(question_id: 15, correct: false, body: "the <v> element.", display_sequence: 0)
Answer.create!(question_id: 15, correct: false, body: "the <l> element.", display_sequence: 0)
Answer.create!(question_id: 15, correct: false, body: "the <p> element.", display_sequence: 0)
Answer.create!(question_id: 15, correct: false, body: "the <m> element.", display_sequence: 0)
Answer.create!(question_id: 15, correct: false, body: "the <n> element.", display_sequence: 0)
Answer.create!(question_id: 15, correct: false, body: "the <t> element.", display_sequence: 0)
Answer.create!(question_id: 15, correct: false, body: "the <w> element.", display_sequence: 0)
Answer.create!(question_id: 15, correct: false, body: "the <b> element.", display_sequence: 0)
Answer.create!(question_id: 15, correct: false, body: "the <j> element.", display_sequence: 0)
Answer.create!(question_id: 16, correct: true, body: "the href attribute.", display_sequence: 0)
Answer.create!(question_id: 16, correct: false, body: "the wrap attribute.", display_sequence: 0)
Answer.create!(question_id: 16, correct: false, body: "the width attribute.", display_sequence: 0)
Answer.create!(question_id: 16, correct: false, body: "the value attribute.", display_sequence: 0)
Answer.create!(question_id: 16, correct: false, body: "the type attribute.", display_sequence: 0)
Answer.create!(question_id: 16, correct: false, body: "the title attribute.", display_sequence: 0)
Answer.create!(question_id: 16, correct: false, body: "the srcset attribute.", display_sequence: 0)
Answer.create!(question_id: 16, correct: false, body: "the src attribute.", display_sequence: 0)
Answer.create!(question_id: 16, correct: false, body: "the required attribute.", display_sequence: 0)
Answer.create!(question_id: 16, correct: false, body: "the rel attribute.", display_sequence: 0)
Answer.create!(question_id: 16, correct: false, body: "the target attribute.", display_sequence: 0)
Answer.create!(question_id: 16, correct: false, body: "the referrerpolicy attribute.", display_sequence: 0)
Answer.create!(question_id: 16, correct: false, body: "the hreflang attribute.", display_sequence: 0)
Answer.create!(question_id: 16, correct: false, body: "the dowload attibute.", display_sequence: 0)
Answer.create!(question_id: 16, correct: false, body: "the upload attribute.", display_sequence: 0)
Answer.create!(question_id: 17, correct: true, body: "with an email address in the to field.", display_sequence: 0)
Answer.create!(question_id: 17, correct: false, body: "with an email address in the bo field.", display_sequence: 0)
Answer.create!(question_id: 17, correct: false, body: "with an email address in the do field.", display_sequence: 0)
Answer.create!(question_id: 17, correct: false, body: "with an email address in the go field.", display_sequence: 0)
Answer.create!(question_id: 17, correct: false, body: "with an email address in the lo field.", display_sequence: 0)
Answer.create!(question_id: 17, correct: false, body: "with an email address in the mo field.", display_sequence: 0)
Answer.create!(question_id: 17, correct: false, body: "with an email address in the no field.", display_sequence: 0)
Answer.create!(question_id: 17, correct: false, body: "with an email address in the so field.", display_sequence: 0)
Answer.create!(question_id: 17, correct: false, body: "with an email address in the vo field.", display_sequence: 0)
Answer.create!(question_id: 17, correct: false, body: "with an email address in the wo field.", display_sequence: 0)
Answer.create!(question_id: 17, correct: false, body: "with an email address in the xo field.", display_sequence: 0)
Answer.create!(question_id: 17, correct: false, body: "with an email address in the yo field.", display_sequence: 0)
Answer.create!(question_id: 17, correct: false, body: "with an email address in the zo field.", display_sequence: 0)
Answer.create!(question_id: 17, correct: false, body: "with an email address in the co field.", display_sequence: 0)
Answer.create!(question_id: 17, correct: false, body: "with an email address in the fo field.", display_sequence: 0)
Answer.create!(question_id: 18, correct: true, body: "elements within a page that can be linked to.", display_sequence: 0)
Answer.create!(question_id: 18, correct: false, body: "intergers within a page that can be linked to.", display_sequence: 0)
Answer.create!(question_id: 18, correct: false, body: "strings within a page that can be linked to.", display_sequence: 0)
Answer.create!(question_id: 18, correct: false, body: "data within a page that can be linked to.", display_sequence: 0)
Answer.create!(question_id: 18, correct: false, body: "binary items within a page that can be linked to.", display_sequence: 0)
Answer.create!(question_id: 18, correct: false, body: "colors within a page that can be linked to.", display_sequence: 0)
Answer.create!(question_id: 18, correct: false, body: "images within a page that can be linked to.", display_sequence: 0)
Answer.create!(question_id: 18, correct: false, body: "documents within a page that can be linked to.", display_sequence: 0)
Answer.create!(question_id: 18, correct: false, body: "color-marks within a page that can be linked to.", display_sequence: 0)
Answer.create!(question_id: 18, correct: false, body: "notes within a page that can be linked to.", display_sequence: 0)
Answer.create!(question_id: 18, correct: false, body: "source code within a page that can be linked to.", display_sequence: 0)
Answer.create!(question_id: 18, correct: false, body: "JavaScript code within a page that can be linked to.", display_sequence: 0)
Answer.create!(question_id: 18, correct: false, body: "Web-data within a page that can be linked to.", display_sequence: 0)
Answer.create!(question_id: 18, correct: false, body: "important characters within a page that can be linked to.", display_sequence: 0)
Answer.create!(question_id: 18, correct: false, body: "real attributes within a page that can be linked to.", display_sequence: 0)
Answer.create!(question_id: 19, correct: true, body: "The <img> element.", display_sequence: 0)
Answer.create!(question_id: 19, correct: false, body: "The <head> element.", display_sequence: 0)
Answer.create!(question_id: 19, correct: false, body: "The <title> element.", display_sequence: 0)
Answer.create!(question_id: 19, correct: false, body: "The <body> element.", display_sequence: 0)
Answer.create!(question_id: 19, correct: false, body: "The <header> element.", display_sequence: 0)
Answer.create!(question_id: 19, correct: false, body: "The <footer> element.", display_sequence: 0)
Answer.create!(question_id: 19, correct: false, body: "The <article> element.", display_sequence: 0)
Answer.create!(question_id: 19, correct: false, body: "The <div> element.", display_sequence: 0)
Answer.create!(question_id: 19, correct: false, body: "The <span> element.", display_sequence: 0)
Answer.create!(question_id: 19, correct: false, body: "The <audio> element.", display_sequence: 0)
Answer.create!(question_id: 19, correct: false, body: "The <canvas> element.", display_sequence: 0)
Answer.create!(question_id: 19, correct: false, body: "The <details> element.", display_sequence: 0)
Answer.create!(question_id: 19, correct: false, body: "The <nav> element.", display_sequence: 0)
Answer.create!(question_id: 19, correct: false, body: "The <output> element.", display_sequence: 0)
Answer.create!(question_id: 19, correct: false, body: "The <progress> element.", display_sequence: 0)
Answer.create!(question_id: 20, correct: true, body: "The src attribute.", display_sequence: 0)
Answer.create!(question_id: 20, correct: false, body: "the wrap attribute.", display_sequence: 0)
Answer.create!(question_id: 20, correct: false, body: "the width attribute.", display_sequence: 0)
Answer.create!(question_id: 20, correct: false, body: "the value attribute.", display_sequence: 0)
Answer.create!(question_id: 20, correct: false, body: "the type attribute.", display_sequence: 0)
Answer.create!(question_id: 20, correct: false, body: "the title attribute.", display_sequence: 0)
Answer.create!(question_id: 20, correct: false, body: "the srcset attribute.", display_sequence: 0)
Answer.create!(question_id: 20, correct: false, body: "the alt attribute.", display_sequence: 0)
Answer.create!(question_id: 20, correct: false, body: "the required attribute.", display_sequence: 0)
Answer.create!(question_id: 20, correct: false, body: "the rel attribute.", display_sequence: 0)
Answer.create!(question_id: 20, correct: false, body: "the target attribute.", display_sequence: 0)
Answer.create!(question_id: 20, correct: false, body: "the referrerpolicy attribute.", display_sequence: 0)
Answer.create!(question_id: 20, correct: false, body: "the hreflang attribute.", display_sequence: 0)
Answer.create!(question_id: 20, correct: false, body: "the dowload attibute.", display_sequence: 0)
Answer.create!(question_id: 20, correct: false, body: "the upload attribute.", display_sequence: 0)
Answer.create!(question_id: 21, correct: true, body: "The alt attribute.", display_sequence: 0)
Answer.create!(question_id: 21, correct: false, body: "the wrap attribute.", display_sequence: 0)
Answer.create!(question_id: 21, correct: false, body: "the width attribute.", display_sequence: 0)
Answer.create!(question_id: 21, correct: false, body: "the value attribute.", display_sequence: 0)
Answer.create!(question_id: 21, correct: false, body: "the type attribute.", display_sequence: 0)
Answer.create!(question_id: 21, correct: false, body: "the title attribute.", display_sequence: 0)
Answer.create!(question_id: 21, correct: false, body: "the srcset attribute.", display_sequence: 0)
Answer.create!(question_id: 21, correct: false, body: "the src attribute.", display_sequence: 0)
Answer.create!(question_id: 21, correct: false, body: "the required attribute.", display_sequence: 0)
Answer.create!(question_id: 21, correct: false, body: "the rel attribute.", display_sequence: 0)
Answer.create!(question_id: 21, correct: false, body: "the target attribute.", display_sequence: 0)
Answer.create!(question_id: 21, correct: false, body: "the referrerpolicy attribute.", display_sequence: 0)
Answer.create!(question_id: 21, correct: false, body: "the hreflang attribute.", display_sequence: 0)
Answer.create!(question_id: 21, correct: false, body: "the dowload attibute.", display_sequence: 0)
Answer.create!(question_id: 21, correct: false, body: "the upload attribute.", display_sequence: 0)
Answer.create!(question_id: 22, correct: true, body: "JPEGs", display_sequence: 0)
Answer.create!(question_id: 22, correct: false, body: "PNG", display_sequence: 0)
Answer.create!(question_id: 22, correct: false, body: "APNG", display_sequence: 0)
Answer.create!(question_id: 22, correct: false, body: "SVG", display_sequence: 0)
Answer.create!(question_id: 22, correct: false, body: "BMP", display_sequence: 0)
Answer.create!(question_id: 22, correct: false, body: "BMP ICO", display_sequence: 0)
Answer.create!(question_id: 22, correct: false, body: "PNG ICO", display_sequence: 0)
Answer.create!(question_id: 22, correct: false, body: "EXIF", display_sequence: 0)
Answer.create!(question_id: 22, correct: false, body: "TIFF", display_sequence: 0)
Answer.create!(question_id: 22, correct: false, body: "PPM", display_sequence: 0)
Answer.create!(question_id: 22, correct: false, body: "BAT", display_sequence: 0)
Answer.create!(question_id: 22, correct: false, body: "BPG", display_sequence: 0)
Answer.create!(question_id: 22, correct: false, body: "CGM", display_sequence: 0)
Answer.create!(question_id: 22, correct: false, body: "WEBP", display_sequence: 0)
Answer.create!(question_id: 22, correct: false, body: "HDR", display_sequence: 0)
Answer.create!(question_id: 23, correct: true, body: "GIFs", display_sequence: 0)
Answer.create!(question_id: 23, correct: false, body: "PNG", display_sequence: 0)
Answer.create!(question_id: 23, correct: false, body: "APNG", display_sequence: 0)
Answer.create!(question_id: 23, correct: false, body: "SVG", display_sequence: 0)
Answer.create!(question_id: 23, correct: false, body: "BMP", display_sequence: 0)
Answer.create!(question_id: 23, correct: false, body: "BMP ICO", display_sequence: 0)
Answer.create!(question_id: 23, correct: false, body: "PNG ICO", display_sequence: 0)
Answer.create!(question_id: 23, correct: false, body: "EXIF", display_sequence: 0)
Answer.create!(question_id: 23, correct: false, body: "TIFF", display_sequence: 0)
Answer.create!(question_id: 23, correct: false, body: "PPM", display_sequence: 0)
Answer.create!(question_id: 23, correct: false, body: "BAT", display_sequence: 0)
Answer.create!(question_id: 23, correct: false, body: "BPG", display_sequence: 0)
Answer.create!(question_id: 23, correct: false, body: "CGM", display_sequence: 0)
Answer.create!(question_id: 23, correct: false, body: "WEBP", display_sequence: 0)
Answer.create!(question_id: 23, correct: false, body: "HDR", display_sequence: 0)
Answer.create!(question_id: 24, correct: true, body: "The <table> element.", display_sequence: 0)
Answer.create!(question_id: 24, correct: false, body: "The <head> element.", display_sequence: 0)
Answer.create!(question_id: 24, correct: false, body: "The <title> element.", display_sequence: 0)
Answer.create!(question_id: 24, correct: false, body: "The <body> element.", display_sequence: 0)
Answer.create!(question_id: 24, correct: false, body: "The <header> element.", display_sequence: 0)
Answer.create!(question_id: 24, correct: false, body: "The <footer> element.", display_sequence: 0)
Answer.create!(question_id: 24, correct: false, body: "The <article> element.", display_sequence: 0)
Answer.create!(question_id: 24, correct: false, body: "The <div> element.", display_sequence: 0)
Answer.create!(question_id: 24, correct: false, body: "The <span> element.", display_sequence: 0)
Answer.create!(question_id: 24, correct: false, body: "The <audio> element.", display_sequence: 0)
Answer.create!(question_id: 24, correct: false, body: "The <canvas> element.", display_sequence: 0)
Answer.create!(question_id: 24, correct: false, body: "The <details> element.", display_sequence: 0)
Answer.create!(question_id: 24, correct: false, body: "The <nav> element.", display_sequence: 0)
Answer.create!(question_id: 24, correct: false, body: "The <output> element.", display_sequence: 0)
Answer.create!(question_id: 24, correct: false, body: "The <progress> element.", display_sequence: 0)
puts Answer.count